export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as AddLesson } from "./AddLesson";
export { default as ModalComponent } from "./addLessonComponents/Modal";
export { default as StepsComponent } from "./addLessonComponents/Modal/Steps";
export { default as Timeform } from "./addLessonComponents/Modal/Steps/Timeform";
export { default as Lessonform} from "./addLessonComponents/Modal/Steps/Lessonform";
export { default as Schoolform } from "./addLessonComponents/Modal/Steps/Schoolform";
export { default as Teacherform } from "./addLessonComponents/Modal/Steps/Teacherform";